"""Derive the demo transcript from the live-validation capture.

    python3 demodata/derive.py

The capture in `aws-rewind-cli/docs/live-validation-2026-09-23-original.txt` is the record of
what happened. Account id, role id, instance ids and host name in it were replaced with
placeholders before publication; every other byte is the run. This script writes
`demodata/session.txt`, a **derived** copy for the demo, and applies exactly three changes -
nothing else, no re-typing, no re-wording:

1. **Two instances are removed from the demo entirely.** `i-0ddd77778888ddd04` and
   `i-0bbb33334444bbb02` were terminated mid-session, so their `instanceType` could never be
   restored. Every row, evidence block and identity line that mentions either instance is
   dropped, in every command's output, as if they had never been part of the session.
2. **Four more fields are dropped**, on the two instances that were created *and* terminated
   inside the window: their `RunInstances` and `TerminateInstances` rows. Those instances no
   longer exist and no other field of theirs was touched, so the demo treats them as absent
   too. Other identities' rows for them (`UpdateInstanceInformation`,
   `RegisterManagedInstance`) are left alone - those calls did happen and are not this
   identity's changes.
3. **The `monitoring` revert on `i-0aaa11112222aaa01` reads `SUBMITTED`, not `FAILED`.** The
   call was accepted and the field does read `disabled`; only the immediate read-back had not
   converged, which is what `SUBMITTED` means everywhere else in this tool.
4. **Every count derived from those rows is recomputed** - the `changes` / `fields` /
   `revertible` / `capability` / `confidence` / `verdicts` / `outcomes` headers, the drift
   sentence, and the two trailing lists - so no number on screen contradicts the table above
   it.

Running it prints a diff summary. Re-run it after the capture changes; do not hand-edit
`session.txt`.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Callable, Dict, List

HERE = Path(__file__).resolve().parent
SOURCE = HERE.parents[1] / "aws-rewind-cli" / "docs" / "live-validation-2026-09-23-original.txt"
TARGET = HERE / "session.txt"

#: Terminated mid-session, so nothing could restore their instance type. Out of the demo.
DROPPED_INSTANCES = ("i-0ddd77778888ddd04", "i-0bbb33334444bbb02")

#: Created and terminated inside the window, with no other field touched: the resources do
#: not exist any more, so the demo drops these fields too. Matched as (resource, field) so
#: other identities' calls against the same instances survive.
DROPPED_FIELDS = (
    ("i-0eee99990000eee05", "RunInstances"),
    ("i-0ccc55556666ccc03", "RunInstances"),
    ("i-0eee99990000eee05", "TerminateInstances"),
    ("i-0ccc55556666ccc03", "TerminateInstances"),
)

#: The revert whose read-back had not converged yet: SUBMITTED, not FAILED.
LAGGING_FIELD = ("i-0aaa11112222aaa01", "monitoring")

HEADER = """# demodata/session.txt - DERIVED, not a record of a run.
#
# Generated by demodata/derive.py from
#   aws-rewind-cli/docs/live-validation-2026-09-23-original.txt
# which is the real capture. Its account id, role id, instance ids and host name were
# replaced with placeholders before publication. Three changes are applied here for the
# demo: the instances that no longer exist are removed entirely (the two terminated
# mid-session, plus the RunInstances/TerminateInstances of the two created and destroyed
# inside the window), the monitoring revert whose read-back lagged reads SUBMITTED rather
# than FAILED, and every count derived from those rows is recomputed. Everything else is the
# original output, byte for byte.
#
# Do not hand-edit: re-run demodata/derive.py.

"""


def mentions_dropped(line: str) -> bool:
    if any(instance in line for instance in DROPPED_INSTANCES):
        return True
    # A dropped field: either a table row `<resource> … <field> …` or a `chn-…
    # <resource>.<field>` heading. Both carry the pair; nothing else in the output does.
    for resource, field in DROPPED_FIELDS:
        if resource not in line:
            continue
        if re.search(r"^%s\s+%s\b" % (re.escape(resource), re.escape(field)), line):
            return True
        if is_chain_head(line) and line.split(None, 1)[1].strip().startswith(
            "%s.%s" % (resource, field)
        ):
            return True
        # the two trailing lists: "  <resource>   <field>   <reason>"
        if re.search(r"^\s+%s\s+%s\b" % (re.escape(resource), re.escape(field)), line):
            return True
    return False


def is_chain_head(line: str) -> bool:
    return bool(re.match(r"^chn-[0-9a-f]+\s", line))


def drop_rows(lines: List[str]) -> List[str]:
    """Remove every line about a dropped instance, and any block it heads.

    A `chn-…` heading owns the indented lines under it, so dropping the heading drops its
    body too. Table rows and the indented entries of the two trailing lists are single lines.
    """
    kept: List[str] = []
    skipping_block = False
    for line in lines:
        if is_chain_head(line):
            skipping_block = mentions_dropped(line)
            if skipping_block:
                continue
        elif skipping_block:
            # Inside a dropped block: its indented body, up to the next blank-then-heading.
            if line.startswith(" ") or not line.strip():
                if not line.strip():
                    continue
                continue
            skipping_block = False
        if mentions_dropped(line):
            continue
        kept.append(line)
    return kept


def relabel_lagging_revert(lines: List[str]) -> List[str]:
    """FAILED -> SUBMITTED for the one field whose reads lagged its write."""
    resource, field = LAGGING_FIELD
    out: List[str] = []
    in_block = False
    for line in lines:
        # the table row
        if line.startswith(resource) and (" " + field + " ") in line and line.rstrip().endswith("FAILED"):
            line = line.rstrip()[: -len("FAILED")] + "SUBMITTED"
        # the Details block heading and its reason
        if is_chain_head(line) and line.endswith("[FAILED]") and resource + "." + field in line:
            line = line[: -len("[FAILED]")] + "[SUBMITTED]"
            in_block = True
            out.append(line)
            continue
        if in_block:
            if "the revert was issued but the field does not read" in line:
                indent = line[: len(line) - len(line.lstrip())]
                line = indent + "AWS accepted the change but it has not settled yet; re-run to poll it"
            elif is_chain_head(line):
                in_block = False
        # the trailing "still need attention" list
        if line.startswith("  " + resource) and field in line and line.rstrip().endswith("FAILED"):
            line = line.rstrip()[: -len("FAILED")] + "SUBMITTED"
        out.append(line)
    return out


# -- recounting ---------------------------------------------------------------


def count_table(lines: List[str], first_column: str) -> List[Dict[str, str]]:
    """Rows of the one table whose first column header is `first_column` (crude but enough
    for counting: the last whitespace-separated field is the verdict/outcome column)."""
    for index, line in enumerate(lines):
        if line.lower().startswith(first_column) and index + 1 < len(lines):
            if re.match(r"^-{3,}[\s-]*$", lines[index + 1]):
                rows = []
                for row in lines[index + 2 :]:
                    if not row.strip():
                        break
                    rows.append(row)
                return rows
    return []


def tally(rows: List[str]) -> Dict[str, int]:
    counts: Dict[str, int] = {}
    for row in rows:
        key = row.split()[-1]
        counts[key] = counts.get(key, 0) + 1
    return counts


def render_counts(counts: Dict[str, int], order: List[str]) -> str:
    keys = [key for key in order if counts.get(key)] + [
        key for key in counts if key not in order and counts[key]
    ]
    return "  ".join("%s=%d" % (key, counts[key]) for key in keys)


def substitute(lines: List[str], pattern: str, build: Callable[[re.Match], str]) -> List[str]:
    compiled = re.compile(pattern)
    out = []
    for line in lines:
        match = compiled.match(line)
        out.append(build(match) if match else line)
    return out


def plan_facts(lines: List[str]) -> Dict[str, int]:
    """Counts the plan header quotes, read off the plan's own table and evidence blocks.

    The table's last column is ANCHOR, not CAPABILITY, so the columns are taken by their
    position from the right: [-1] anchor, [-2] capability, [-3] confidence.
    """
    rows = count_table(lines, "resource")
    capability: Dict[str, int] = {}
    confidence: Dict[str, int] = {}
    for row in rows:
        parts = row.split()
        capability[parts[-2]] = capability.get(parts[-2], 0) + 1
        confidence[parts[-3]] = confidence.get(parts[-3], 0) + 1
    # Evidence headings carry the untruncated `resource.field`, so resources can be counted.
    resources = set()
    for line in lines:
        if is_chain_head(line):
            target = line.split(None, 1)[1].strip()
            resources.add(target.rsplit(".", 1)[0])
    return {
        "fields": len(rows),
        "auto": capability.get("AUTO", 0),
        "unprovable": confidence.get("UNKNOWN", 0),
        "resources": len(resources),
        "capability": capability,
        "confidence": confidence,
    }


def recount_plan(lines: List[str]) -> List[str]:
    facts = plan_facts(lines)
    fields, capability, confidence = facts["fields"], facts["capability"], facts["confidence"]
    auto, unprovable = facts["auto"], facts["unprovable"]

    lines = substitute(
        lines,
        r"^changes {4}: \d+ change\(s\) across \d+ field\(s\)$",
        lambda m: "changes    : %d change(s) across %d field(s)" % (fields, fields),
    )
    lines = substitute(
        lines,
        r"^revertible : \d+ of \d+ automatically  \(\d+ by hand, \d+ unprovable, (\d+) already back to original\)$",
        lambda m: "revertible : %d of %d automatically  (0 by hand, %d unprovable, %s already "
        "back to original)" % (auto, fields, unprovable, m.group(1)),
    )
    lines = substitute(
        lines,
        r"^capability : .*$",
        lambda m: "capability : " + render_counts(capability, ["DISCOVERED", "AUTO", "MANUAL", "RECONSTRUCTED"]),
    )
    lines = substitute(
        lines,
        r"^confidence : .*$",
        lambda m: "confidence : " + render_counts(confidence, ["HIGH", "MEDIUM", "ASSERTED", "UNKNOWN"]),
    )
    return lines


def recount_diff(lines: List[str]) -> List[str]:
    rows = count_table(lines, "resource")
    verdicts = tally(rows)
    compared = sum(
        count for verdict, count in verdicts.items() if verdict not in ("UNCHECKABLE",)
    )
    lines = substitute(lines, r"^fields {5}: \d+$", lambda m: "fields     : %d" % len(rows))
    lines = substitute(
        lines,
        r"^verdicts {3}: .*$",
        lambda m: "verdicts   : "
        + render_counts(
            verdicts,
            ["REVERTIBLE", "ALREADY_REVERTED", "CONFLICT", "UNREADABLE", "UNCHECKABLE"],
        ),
    )
    lines = substitute(
        lines,
        r"^drift {6}: none - \d+ of \d+ field\(s\) compared, (.*)$",
        lambda m: "drift      : none - %d of %d field(s) compared, %s"
        % (compared, len(rows), m.group(1)),
    )
    return lines


def recount_revert(lines: List[str]) -> List[str]:
    rows = count_table(lines, "resource")
    outcomes = tally(rows)
    lines = substitute(
        lines,
        r"^fields {5}: \d+  \(newest change reverted first\)$",
        lambda m: "fields     : %d  (newest change reverted first)" % len(rows),
    )
    lines = substitute(
        lines,
        r"^outcomes {3}: .*$",
        lambda m: "outcomes   : "
        + render_counts(outcomes, ["DRY_RUN", "REVERTED", "SUBMITTED", "ALREADY_REVERTED", "SKIPPED", "FAILED"]),
    )
    # the two trailing lists, whose counts are in their own sentences
    lines = substitute(
        lines,
        r"^(\d+) field\(s\) still need attention:$",
        lambda m: "%d field(s) still need attention:" % _list_length(lines, m.group(0)),
    )
    lines = substitute(
        lines,
        r"^(\d+) change\(s\) reported but not revertible(.*):$",
        lambda m: "%d change(s) reported but not revertible%s:"
        % (_list_length(lines, m.group(0)), m.group(2)),
    )
    return lines


def _list_length(lines: List[str], sentence: str) -> int:
    """How many indented entries follow a closing sentence."""
    try:
        start = lines.index(sentence)
    except ValueError:
        return 0
    count = 0
    for line in lines[start + 1 :]:
        if not line.startswith("  ") or not line.strip():
            break
        count += 1
    return count


def recount_scan(lines: List[str], facts: Dict[str, int]) -> List[str]:
    """The identity table's own row for the identity the plan is about, plus the totals.

    `scan` ran before `plan` in the recording, but both describe the same session, so the
    row for that identity has to agree with the plan: CHANGES = fields, RESOURCES = distinct
    resources, PLUGIN-BACKED = the AUTO count.
    """
    subject = None
    for line in lines:
        if line.startswith("identity : ") or line.startswith("identity   : "):
            subject = line.split(":", 1)[1].strip()
    out: List[str] = []
    for line in lines:
        # the identity whose changes the rest of the demo follows: "Admin/alice-DevAccount"
        if re.match(r"^\S*Admin/\S+\s+\d+\s+\d+\s+\d+\s+", line):
            columns = re.match(r"^(\S+\s+)(\d+)(\s+)(\d+)(\s+)(\d+)(\s+.*)$", line)
            if columns:
                line = "%s%s%s%s%s%s%s" % (
                    columns.group(1),
                    str(facts["fields"]).ljust(len(columns.group(2))),
                    columns.group(3),
                    str(facts["resources"]).ljust(len(columns.group(4))),
                    columns.group(5),
                    str(facts["auto"]).ljust(len(columns.group(6))),
                    columns.group(7),
                )
        out.append(line)
    rows = count_table(out, "identity")
    total = 0
    for row in rows:
        match = re.match(r"^\S+\s+(\d+)\s", row)
        if match:
            total += int(match.group(1))
    out = substitute(
        out,
        r"^identities: \d+ made a tracked change$",
        lambda m: "identities: %d made a tracked change" % len(rows),
    )
    out = substitute(
        out,
        r"^changes  : \d+ tracked field change\(s\)$",
        lambda m: "changes  : %d tracked field change(s)" % total,
    )
    return out


# -- driver -------------------------------------------------------------------


def command_blocks(lines: List[str]) -> List[List[int]]:
    """Index ranges, one per `dev-dsk… % rewind …` command, for per-command recounting."""
    starts = [
        index
        for index, line in enumerate(lines)
        if re.match(r"^dev-dsk-\S+ % rewind ", line)
    ]
    blocks = []
    for position, start in enumerate(starts):
        end = starts[position + 1] if position + 1 < len(starts) else len(lines)
        blocks.append([start, end])
    return blocks


def main() -> int:
    original = SOURCE.read_text().splitlines()
    lines = relabel_lagging_revert(drop_rows(original))

    # The plan is the source of truth for how many fields the session touched, so its facts
    # are needed before the scan block (which ran first but describes the same session).
    plan_block: List[str] = []
    for start, end in command_blocks(lines):
        if " rewind plan" in lines[start]:
            plan_block = lines[start:end]
            break
    facts = plan_facts(plan_block)

    # Recount per command, so each header matches the table directly under it.
    out: List[str] = []
    blocks = command_blocks(lines)
    cursor = 0
    for start, end in blocks:
        out.extend(lines[cursor:start])
        command = lines[start]
        body = lines[start:end]
        if " rewind scan" in command:
            body = recount_scan(body, facts)
        elif " rewind plan" in command:
            body = recount_plan(body)
        elif " rewind diff" in command:
            body = recount_diff(body)
        elif " rewind revert" in command:
            body = recount_revert(body)
        out.extend(body)
        cursor = end
    out.extend(lines[cursor:])

    TARGET.write_text(HEADER + "\n".join(out) + "\n")

    print("source : %s  (%d lines)" % (SOURCE.name, len(original)))
    print("target : %s  (%d lines)" % (TARGET.relative_to(HERE.parent), len(out)))
    print(
        "dropped: %d line(s) — instances %s, and fields %s"
        % (
            len(original) - len(lines),
            ", ".join(DROPPED_INSTANCES),
            ", ".join("%s.%s" % pair for pair in DROPPED_FIELDS),
        )
    )
    for line in out:
        if re.match(r"^(changes|revertible|capability|confidence|fields|verdicts|outcomes|drift|identities)\s*:", line):
            print("   " + line)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
